### ISSUE TITLE
[thegraph][bug] deposit id/tx wrong

### ISSUE THREAD

**Issue by sakulstra** [aave/aave-protocol#3]
According to https://github.com/aave/aave-protocol/blob/master/thegraph/formatted/schema.graphql#L129 the `id` should be the `tx`, but running
```
{
  deposits{
    id
  }
}
```
returns
```
"data": {
    "deposits": [
      {
        "id": "0x00001b59a28c28623982fa110b2a27d4a9b018633c07b650f2c43244e8afc5b9d"
      }
   ],...
}
```
Where the `tx` is apparently suffixed with a `d` https://github.com/aave/aave-protocol/blob/master/thegraph/raw/mapping/lending-pool.ts#L167

**Comment by kyzia551** [comment]
Hello @sakulstra !

Thank you very much for research. I will remove this "d" letter soon.

The issue is related to that I used a common interface for the most part of the pool operations, which is not allowing to use same id for different entities compatible with this interface

Is it matter for you to have direct access to pool interactions by txHash? Because the main problem is that it could be more than 1 deposit in the same tx, and I'm thinking about how to make this id unique and easily accessable for end users. Is the idea with numbers after txHash like 
```id: txHash + 0..9``` will fit for you?

**Comment by sakulstra** [comment]
@kyzia551 I just noticed it when trying to link the deposit transactions on aavewatch.now.sh to the corresponding etherscan transaction.

While this would work for me, i'd prefer having id as sth unique (I don't really care to much how it is constructed- but i guess 0..9 would fall short when more than 9 deposits are done in a single transaction?), but also having the `tx` as part of the payload.

```
id: ID! # some unique id
tx: ID! # not necessarily unique tx hash
```
